#!/bin/bash
export CC=armv7-psc-linux-gnueabihf-gcc
export CXX=armv7-psc-linux-gnueabihf-g++
export RANLIB=armv7-psc-linux-gnueabihf-ranlib

export CFLAGS=-I/home/screemer/x-tools/armv8-sony-linux-gnueabihf/armv8-sony-linux-gnueabihf/sysroot/usr/include

make -j4 PLATFORM=rpi2-sdl2
